### PR TITLE
Extension/show repaired tests

### LINKED ISSUE #50: [Report] Visualize of 'repaired' tests
**Is your feature request related to a problem? Please describe.**
When a test annotated with `@Fails` is passed because the corresponding bug was solved, the user should informed about that. In that case he should remove the annoation. The classic report lists these tests on the dashboard.

**Describe the solution you'd like**
In the new report I'm missing such a filter. I suggest the following solution:
- On the dashboard a new box is added when repaired tests exist.
- This box can be placed under 'Tests: x'.
- This box contains a link to 'Tests' area with a predefined filter.
- The method defails should handle 'repaired' tests. At the moment the annoation is shown under the `Passed`. The user should informed that he can remove the `@Fails` annotation.

_or_: This link can added to the existing box 'Tests: x'

### PR DESCRIPTION
**Pull request by mreiche**
# Description

Show count of repaired tests as sup relation of passed tests in dashboard.
image

Added new custom temporary status "Repaired" in tests view.
image

Fixes #50

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by gogro — DISMISSED** [review]
trust approval

**Review by erickubenka — APPROVED** [review]

**Review by mbeuthan — APPROVED** [review]

**Comment by martingrossmann** [comment]
In my mind the status filter on test overview is inconsistent. 
For examle you have passed tests which include retried and repaired tests:
* Retried tests have no specific filter in status selection
* Repaired tests have a specific filter

Filtering for `Passed` also retried and repaired tests are shown. Its not clear after which criterias the status filter list was created.

Therfore the status list should only contain real test status like `Failed`, `Expected failed`, `Skipped`, `Passed`.

Retried (passed or failed) and repaired are attributes of a test, not status values. So tests should have a flag showing special attributes. The filter for tests should handle this similar to `Show configuration methods` filter.

**Review by mbeuthan — APPROVED** [review]

**Comment by mreiche** [comment]
> In my mind the status filter on test overview is inconsistent.
> For examle you have passed tests which include retried and repaired tests:
> 
> * Retried tests have no specific filter in status selection
> * Repaired tests have a specific filter
> 
> Filtering for `Passed` also retried and repaired tests are shown. Its not clear after which criterias the status filter list was created.
> 
> Therfore the status list should only contain real test status like `Failed`, `Expected failed`, `Skipped`, `Passed`.
> 
> Retried (passed or failed) and repaired are attributes of a test, not status values. So tests should have a flag showing special attributes. The filter for tests should handle this similar to `Show configuration methods` filter.

Problem is, that you cannot easily say "show retried tests", because in comparison to "show configuration methods", these are not a separated amount of the tests relation.

For example:
* Clicking the button "show configuration methods", shows mores.
* Click the button "show repaired tests" shows only repaired tests? Feels wrong in forms of usuability.

Thats why a made the following decision:
* I introduced the virtual status: "Repaired".
* Unlike "Failed Expected": "Repaired" is a "Passed" tests with `@Fails` annotation.
* For comparison: "Failed Expected" is a "Failed" test with `@Fails` annotation.
* Thats why having a virtual status like that is right.

The "inconsistency" comes from:
* "Failed Expected" is more relevant than "Repaired"
* We may add the general status "Repaired" next to "Failed Expected"
* "Failed Expected" is part of the core test result status model, "Repaired" not

Suggestions for future change:
* Remove "Failed Expected" as actual status and make it virtual
* Or: Add "Repaired" as actual status and make it non-virtual in the report

For my personally: Its better to have virtual statuses instead of hard test statuses like "Repaired" or "Failed Expected". However, this is a Product Owning discussion.

**Comment by mreiche** [comment]
Added "Repaired" status in method detail:
image

**Review by martingrossmann — APPROVED** [review]

**Review by gogro — APPROVED** [review]

**Pull request merged**
