### PR TITLE
Extension/mdc update

### PR DESCRIPTION
**Pull request by mreiche**
# Description

* MDC-Upgrade from v3 to v7
* General design and layout consistence

**For reviewers:**
* Please perform manual review on your report

### CODE REVIEW

**Comment by martingrossmann** [comment]
The elements on dashboard are mixed and not at the former position:
image

**Comment by mreiche** [comment]
This is wanted to give the Failure Aspects more space.

**Comment by mreiche** [comment]
I've updated the layout for the dashboard.
image
image

**Comment by martingrossmann** [comment]
Yes, looks good!

**Review by martingrossmann — APPROVED** [review]

**Review by mbeuthan — APPROVED** [review]

**Pull request merged**
