### PR TITLE
Refactoring/virtual log view

### PR DESCRIPTION
**Pull request by mreiche**
# Description

1) I've implemented a much more performant log view by integrating ui virtualization, but that comes with a few changes.

- The log text cannot be wrapped anymore, so the lines are very long.
- The log view windows is as large as its content
- The search needed to be refactored, it's not a filter anymore, it tries to find the results and scrolls to its position.

2) Also added loading indicator for Dashboard to indicate long loading times due large datasets.

## Review
**Please check that out locally with your large example data!**
- Goto `report-ng/app`
- Run `npm install`
- Run `npm start`
- Copy your execution model to `static/model`

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by martingrossmann** [comment]
Thanks for rework. The loading of logs is quite fast. 
But the log view changes its width during scrolling, the box flips to small und to a huge width like this:
image
image

Is there a change to define a min-width?

**Comment by mreiche** [comment]
> Thanks for rework. The loading of logs is quite fast.
> 
> 1. But the log view changes its width during scrolling, the box flips to small und to a huge width like this:
>    image
>    image
> 
> Is there a change to define a min-width?
> 
> 1. The search field needs an ENTER for activation. The user needs a hint for it. Could an extra button improve the usability?

It's not possible to define a width or break the content, because the infinite scroll relys on single line height, only the width is variable and changes the content when the line gets rendered into the DOM.

**Comment by martingrossmann** [comment]
> > Thanks for rework. The loading of logs is quite fast.
> > 
> > 1. But the log view changes its width during scrolling, the box flips to small und to a huge width like this:
> >    image
> >    image
> > 
> > Is there a change to define a min-width?
> > 
> > 1. The search field needs an ENTER for activation. The user needs a hint for it. Could an extra button improve the usability?
> 
> It's not possible to define a width or break the content, because the infinite scroll relys on single line height, only the width is variable and changes the content when the line gets rendered into the DOM.

Is there a change to add a fake log box as background to hide the flipping log view?

**Comment by mreiche** [comment]
> > > Thanks for rework. The loading of logs is quite fast.
> > > 
> > > 1. But the log view changes its width during scrolling, the box flips to small und to a huge width like this:
> > >    image
> > >    image
> > > 
> > > Is there a change to define a min-width?
> > > 
> > > 1. The search field needs an ENTER for activation. The user needs a hint for it. Could an extra button improve the usability?
> > 
> > 
> > It's not possible to define a width or break the content, because the infinite scroll relys on single line height, only the width is variable and changes the content when the line gets rendered into the DOM.
> 
> Is there a chance to add a fake log box as background to hide the flipping log view?

Ah, that you mean. Which Browser you use? I tested in Chrome only.

**Comment by martingrossmann** [comment]
> > Is there a chance to add a fake log box as background to hide the flipping log view?
> 
> Ah, that you mean. Which Browser you use? I tested in Chrome only.

I only used Chrome as well.

**Comment by martingrossmann** [comment]
> > > Is there a chance to add a fake log box as background to hide the flipping log view?
> > 
> > 
> > Ah, that you mean. Which Browser you use? I tested in Chrome only.
> 
> I only used Chrome as well.

In Firefox it looks good. The log box has the same width over the complete log. Only the text runs out if its longer.

**Review by martingrossmann — APPROVED** [review]

**Review by mbeuthan — APPROVED** [review]

**Pull request merged**
